const now = new Date().toISOString()
const yesterday = new Date(Date.now() - 86400000).toISOString()
const tomorrow = new Date(Date.now() + 86400000).toISOString()
const nextWeek = new Date(Date.now() + 7 * 86400000).toISOString()
const lastWeek = new Date(Date.now() - 7 * 86400000).toISOString()

export const mockAppointments = [
	{
		id: "apt_001",
		clientId: "usr_client_001",
		clientName: "Pedro Reyes",
		enpId: "usr_enp_001",
		enpName: "Atty. Maria Santos",
		title: "Deed of Sale — Lot 12 Block 5",
		description: "Notarization of deed of absolute sale for residential property.",
		status: "confirmed" as const,
		scheduledAt: tomorrow,
		durationMinutes: 60,
		location: "Room 305, Makati Legal Hub",
		isVirtual: false,
		meetingUrl: null,
		notes: null,
		notarizationType: "acknowledgment" as const,
		sessionMode: "in_person" as const,
		declineReason: null,
		documentsCount: 2,
		canStart: true,
		canRejoin: false,
		createdAt: yesterday,
		updatedAt: yesterday,
	},
	{
		id: "apt_002",
		clientId: "usr_client_002",
		clientName: "Ana Mendoza",
		enpId: "usr_enp_001",
		enpName: "Atty. Maria Santos",
		title: "Special Power of Attorney",
		description: "SPA for bank-related transactions.",
		status: "pending" as const,
		scheduledAt: nextWeek,
		durationMinutes: 30,
		location: null,
		isVirtual: true,
		meetingUrl: "https://meet.qlegal.ph/apt_002",
		notes: null,
		notarizationType: "jurat" as const,
		sessionMode: "remote" as const,
		declineReason: null,
		documentsCount: 0,
		canStart: false,
		canRejoin: false,
		createdAt: now,
		updatedAt: now,
	},
	{
		id: "apt_003",
		clientId: "usr_client_001",
		clientName: "Pedro Reyes",
		enpId: "usr_enp_003",
		enpName: "Atty. Rosa Garcia",
		title: "Affidavit of Loss",
		description: null,
		status: "ended" as const,
		scheduledAt: lastWeek,
		durationMinutes: 30,
		location: "Office 201, Quezon City",
		isVirtual: false,
		meetingUrl: null,
		notes: "Client brought two valid IDs.",
		notarizationType: "copy_certification" as const,
		sessionMode: "in_person" as const,
		declineReason: null,
		documentsCount: 1,
		canStart: false,
		canRejoin: false,
		createdAt: lastWeek,
		updatedAt: lastWeek,
	},
	{
		id: "apt_004",
		clientId: "usr_client_002",
		clientName: "Ana Mendoza",
		enpId: "usr_enp_001",
		enpName: "Atty. Maria Santos",
		title: "Oath of Office",
		description: "Oath-taking ceremony for newly appointed barangay official.",
		status: "cancelled" as const,
		scheduledAt: yesterday,
		durationMinutes: 45,
		location: null,
		isVirtual: true,
		meetingUrl: null,
		notes: "Cancelled by client.",
		notarizationType: "oath_affirmation" as const,
		sessionMode: "remote" as const,
		declineReason: null,
		documentsCount: 0,
		canStart: false,
		canRejoin: false,
		createdAt: lastWeek,
		updatedAt: yesterday,
	},
	{
		id: "apt_005",
		clientId: "usr_client_001",
		clientName: "Pedro Reyes",
		enpId: "usr_enp_001",
		enpName: "Atty. Maria Santos",
		title: "General Power of Attorney",
		description: "GPA for property management.",
		status: "in_session" as const,
		scheduledAt: now,
		durationMinutes: 90,
		location: null,
		isVirtual: true,
		meetingUrl: "https://meet.qlegal.ph/apt_005",
		notes: "Session started on time.",
		notarizationType: "signature_witnessing" as const,
		sessionMode: "remote" as const,
		declineReason: null,
		documentsCount: 3,
		canStart: false,
		canRejoin: true,
		createdAt: yesterday,
		updatedAt: now,
	},
	{
		id: "apt_006",
		clientId: "usr_client_003",
		clientName: "Luis Ramos",
		enpId: "usr_enp_001",
		enpName: "Atty. Maria Santos",
		title: "Affidavit of Two Disinterested Persons",
		description: "Correction of clerical error on birth certificate.",
		status: "declined" as const,
		scheduledAt: nextWeek,
		durationMinutes: 45,
		location: null,
		isVirtual: false,
		meetingUrl: null,
		notes: null,
		notarizationType: "acknowledgment" as const,
		sessionMode: "hybrid" as const,
		declineReason: "Incomplete supporting documents",
		documentsCount: 0,
		canStart: false,
		canRejoin: false,
		createdAt: yesterday,
		updatedAt: yesterday,
	},
]

export const mockSessions = [
	{
		id: "sess_001",
		appointmentId: "apt_003",
		enpId: "usr_enp_003",
		clientId: "usr_client_001",
		clientName: "Pedro Reyes",
		status: "completed" as const,
		startedAt: lastWeek,
		endedAt: lastWeek,
		recordingUrl: "https://storage.qlegal.ph/recordings/sess_001.mp4",
		documentIds: ["reg_002"],
		notes: "Smooth session, no issues.",
		createdAt: lastWeek,
		updatedAt: lastWeek,
	},
	{
		id: "sess_002",
		appointmentId: "apt_005",
		enpId: "usr_enp_001",
		clientId: "usr_client_001",
		clientName: "Pedro Reyes",
		status: "active" as const,
		startedAt: now,
		endedAt: null,
		recordingUrl: null,
		documentIds: [],
		notes: null,
		createdAt: now,
		updatedAt: now,
	},
	{
		id: "sess_003",
		appointmentId: "apt_001",
		enpId: "usr_enp_001",
		clientId: "usr_client_001",
		clientName: "Pedro Reyes",
		status: "scheduled" as const,
		startedAt: null,
		endedAt: null,
		recordingUrl: null,
		documentIds: [],
		notes: null,
		createdAt: yesterday,
		updatedAt: yesterday,
	},
]
