const now = new Date().toISOString()
const yesterday = new Date(Date.now() - 86400000).toISOString()
const lastWeek = new Date(Date.now() - 7 * 86400000).toISOString()
const lastMonth = new Date(Date.now() - 30 * 86400000).toISOString()

export const mockPaymentIntents = [
	{
		id: "pay_001",
		userId: "usr_client_001",
		amount: 2500,
		currency: "PHP",
		status: "succeeded" as const,
		description: "Notarization fee — Deed of Sale",
		referenceNumber: "REF-2024-001",
		paymentMethod: "gcash",
		paidAt: lastMonth,
		createdAt: lastMonth,
		updatedAt: lastMonth,
	},
	{
		id: "pay_002",
		userId: "usr_client_002",
		amount: 1500,
		currency: "PHP",
		status: "pending" as const,
		description: "Notarization fee — SPA",
		referenceNumber: null,
		paymentMethod: null,
		paidAt: null,
		createdAt: yesterday,
		updatedAt: now,
	},
	{
		id: "pay_003",
		userId: "usr_client_001",
		amount: 1000,
		currency: "PHP",
		status: "failed" as const,
		description: "Notarization fee — Affidavit",
		referenceNumber: "REF-2024-003",
		paymentMethod: "card",
		paidAt: null,
		createdAt: lastWeek,
		updatedAt: lastWeek,
	},
	{
		id: "pay_004",
		userId: "usr_client_001",
		amount: 3000,
		currency: "PHP",
		status: "processing" as const,
		description: "Notarization fee — GPA",
		referenceNumber: "REF-2024-004",
		paymentMethod: "bank_transfer",
		paidAt: null,
		createdAt: now,
		updatedAt: now,
	},
	{
		id: "pay_005",
		userId: "usr_client_002",
		amount: 500,
		currency: "PHP",
		status: "refunded" as const,
		description: "Cancelled appointment refund",
		referenceNumber: "REF-2024-005",
		paymentMethod: "gcash",
		paidAt: lastWeek,
		createdAt: lastWeek,
		updatedAt: yesterday,
	},
]
