const now = new Date().toISOString()
const yesterday = new Date(Date.now() - 86400000).toISOString()
const lastWeek = new Date(Date.now() - 7 * 86400000).toISOString()
const lastMonth = new Date(Date.now() - 30 * 86400000).toISOString()

export const mockRegistryActs = [
	{
		id: "reg_001",
		enpId: "usr_enp_001",
		actNumber: "ACT-2024-001",
		actType: "deed_of_sale" as const,
		title: "Deed of Absolute Sale — Lot 12 Block 5, Phase 2",
		parties: [
			{ name: "Pedro Reyes", role: "Vendor" },
			{ name: "Anna Cruz", role: "Vendee" },
		],
		executedAt: lastMonth,
		documentUrl: "https://storage.qlegal.ph/docs/reg_001.pdf",
		documentFileObjectId: null,
		doconchainProjectUuid: null,
		scStatus: "synced" as const,
		scSubmittedAt: lastMonth,
		scSyncedAt: lastMonth,
		scRejectionReason: null,
		scExternalRef: "sc-mock-001",
		appointmentId: null,
		bookNo: null,
		pageNo: null,
		feePhp: null,
		createdAt: lastMonth,
		updatedAt: lastMonth,
	},
	{
		id: "reg_002",
		enpId: "usr_enp_003",
		actNumber: "ACT-2024-002",
		actType: "affidavit" as const,
		title: "Affidavit of Loss — Philippine Passport",
		parties: [{ name: "Pedro Reyes", role: "Affiant" }],
		executedAt: lastWeek,
		documentUrl: "https://storage.qlegal.ph/docs/reg_002.pdf",
		documentFileObjectId: null,
		doconchainProjectUuid: null,
		scStatus: "pending_upload" as const,
		scSubmittedAt: null,
		scSyncedAt: null,
		scRejectionReason: null,
		scExternalRef: null,
		appointmentId: null,
		bookNo: null,
		pageNo: null,
		feePhp: null,
		createdAt: lastWeek,
		updatedAt: lastWeek,
	},
	{
		id: "reg_003",
		enpId: "usr_enp_001",
		actNumber: "ACT-2024-003",
		actType: "special_power_of_attorney" as const,
		title: "SPA for Bank Transactions",
		parties: [
			{ name: "Ana Mendoza", role: "Principal" },
			{ name: "Juan Mendoza", role: "Attorney-in-Fact" },
		],
		executedAt: lastWeek,
		documentUrl: "https://storage.qlegal.ph/docs/reg_003.pdf",
		documentFileObjectId: null,
		doconchainProjectUuid: null,
		scStatus: "rejected" as const,
		scSubmittedAt: lastWeek,
		scSyncedAt: null,
		scRejectionReason: "Missing notarial seal on page 2",
		scExternalRef: null,
		appointmentId: null,
		bookNo: null,
		pageNo: null,
		feePhp: null,
		createdAt: lastWeek,
		updatedAt: yesterday,
	},
	{
		id: "reg_004",
		enpId: "usr_enp_001",
		actNumber: "ACT-2024-004",
		actType: "acknowledgment" as const,
		title: "Acknowledgment — Rental Agreement",
		parties: [
			{ name: "Carlos Tan", role: "Lessor" },
			{ name: "Lisa Ang", role: "Lessee" },
		],
		executedAt: yesterday,
		documentUrl: null,
		documentFileObjectId: null,
		doconchainProjectUuid: null,
		scStatus: "draft" as const,
		scSubmittedAt: null,
		scSyncedAt: null,
		scRejectionReason: null,
		scExternalRef: null,
		appointmentId: null,
		bookNo: null,
		pageNo: null,
		feePhp: null,
		createdAt: yesterday,
		updatedAt: now,
	},
	{
		id: "reg_005",
		enpId: "usr_enp_001",
		actNumber: "ACT-2024-005",
		actType: "oath" as const,
		title: "Oath of Office — Barangay Kagawad",
		parties: [{ name: "Roberto Lim", role: "Affiant" }],
		executedAt: lastMonth,
		documentUrl: "https://storage.qlegal.ph/docs/reg_005.pdf",
		documentFileObjectId: null,
		doconchainProjectUuid: null,
		scStatus: "sync_failed" as const,
		scSubmittedAt: lastMonth,
		scSyncedAt: null,
		scRejectionReason: "SC API timeout during transmission",
		scExternalRef: null,
		appointmentId: null,
		bookNo: null,
		pageNo: null,
		feePhp: null,
		createdAt: lastMonth,
		updatedAt: lastWeek,
	},
	{
		id: "reg_006",
		enpId: "usr_enp_001",
		actNumber: "ACT-2024-006",
		actType: "jurat" as const,
		title: "Jurat — Affidavit of Desistance",
		parties: [{ name: "Elena Bautista", role: "Affiant" }],
		executedAt: yesterday,
		documentUrl: "https://storage.qlegal.ph/docs/reg_006.pdf",
		documentFileObjectId: null,
		doconchainProjectUuid: null,
		scStatus: "uploaded" as const,
		scSubmittedAt: yesterday,
		scSyncedAt: null,
		scRejectionReason: null,
		scExternalRef: null,
		appointmentId: null,
		bookNo: null,
		pageNo: null,
		feePhp: null,
		createdAt: yesterday,
		updatedAt: now,
	},
	{
		id: "reg_007",
		enpId: "usr_enp_002",
		actNumber: "ACT-2024-007",
		actType: "certification" as const,
		title: "Certified True Copy — Articles of Incorporation",
		parties: [{ name: "ABC Holdings Inc.", role: "Requesting Party" }],
		executedAt: yesterday,
		documentUrl: "https://storage.qlegal.ph/docs/reg_007.pdf",
		documentFileObjectId: null,
		doconchainProjectUuid: null,
		scStatus: "pending_review" as const,
		scSubmittedAt: yesterday,
		scSyncedAt: null,
		scRejectionReason: null,
		scExternalRef: null,
		appointmentId: null,
		bookNo: null,
		pageNo: null,
		feePhp: null,
		createdAt: yesterday,
		updatedAt: now,
	},
	{
		id: "reg_008",
		enpId: "usr_enp_004",
		actNumber: "ACT-2024-008",
		actType: "acknowledgment" as const,
		title: "Acknowledgment — Lease Contract",
		parties: [{ name: "Mark Villanueva", role: "Lessee" }],
		executedAt: lastWeek,
		documentUrl: "https://storage.qlegal.ph/docs/reg_008.pdf",
		documentFileObjectId: null,
		doconchainProjectUuid: null,
		scStatus: "approved" as const,
		scSubmittedAt: lastWeek,
		scSyncedAt: null,
		scRejectionReason: null,
		scExternalRef: null,
		appointmentId: null,
		bookNo: null,
		pageNo: null,
		feePhp: null,
		createdAt: lastWeek,
		updatedAt: lastWeek,
	},
]
