const now = new Date().toISOString()
const yesterday = new Date(Date.now() - 86400000).toISOString()
const lastWeek = new Date(Date.now() - 7 * 86400000).toISOString()
const lastMonth = new Date(Date.now() - 30 * 86400000).toISOString()

export const mockUsers = [
	{
		id: "usr_enp_001",
		email: "maria.santos@example.com",
		name: "Atty. Maria Santos",
		role: "enp" as const,
		avatarUrl: null,
		phone: "+63 917 123 4567",
		identityStatus: "verified" as const,
		certificateStatus: "active" as const,
		onboardingStep: "complete" as const,
		commissionNumber: "NC-2024-00123",
		commissionExpiry: "2026-12-31",
		subOrgId: "org_001",
		createdAt: lastMonth,
		updatedAt: yesterday,
	},
	{
		id: "usr_enp_002",
		email: "juan.delacruz@example.com",
		name: "Atty. Juan Dela Cruz",
		role: "enp" as const,
		avatarUrl: null,
		phone: "+63 918 234 5678",
		identityStatus: "pending" as const,
		certificateStatus: "studying" as const,
		onboardingStep: "identity_verification" as const,
		commissionNumber: null,
		commissionExpiry: null,
		subOrgId: null,
		createdAt: lastWeek,
		updatedAt: now,
	},
	{
		id: "usr_enp_003",
		email: "rosa.garcia@example.com",
		name: "Atty. Rosa Garcia",
		role: "enp" as const,
		avatarUrl: null,
		phone: "+63 919 345 6789",
		identityStatus: "rejected" as const,
		certificateStatus: "expired" as const,
		onboardingStep: "identity_verification" as const,
		commissionNumber: "NC-2020-00456",
		commissionExpiry: "2024-06-30",
		subOrgId: "org_002",
		createdAt: lastMonth,
		updatedAt: lastWeek,
	},
	{
		id: "usr_client_001",
		email: "pedro.reyes@example.com",
		name: "Pedro Reyes",
		role: "client" as const,
		avatarUrl: null,
		phone: "+63 920 456 7890",
		identityStatus: "verified" as const,
		certificateStatus: "none" as const,
		onboardingStep: "complete" as const,
		commissionNumber: null,
		commissionExpiry: null,
		subOrgId: null,
		createdAt: lastMonth,
		updatedAt: yesterday,
	},
	{
		id: "usr_client_002",
		email: "ana.mendoza@example.com",
		name: "Ana Mendoza",
		role: "client" as const,
		avatarUrl: null,
		phone: "+63 921 567 8901",
		identityStatus: "unverified" as const,
		certificateStatus: "none" as const,
		onboardingStep: "profile" as const,
		commissionNumber: null,
		commissionExpiry: null,
		subOrgId: null,
		createdAt: yesterday,
		updatedAt: now,
	},
	{
		id: "usr_enp_004",
		email: "carlos.bautista@example.com",
		name: "Atty. Carlos Bautista",
		role: "enp" as const,
		avatarUrl: null,
		phone: "+63 923 111 2233",
		identityStatus: "verified" as const,
		certificateStatus: "passed" as const,
		onboardingStep: "complete" as const,
		commissionNumber: "NC-2023-00987",
		commissionExpiry: "2027-03-31",
		subOrgId: "org_001",
		createdAt: lastMonth,
		updatedAt: yesterday,
	},
	{
		id: "usr_enp_005",
		email: "elena.ramos@example.com",
		name: "Atty. Elena Ramos",
		role: "enp" as const,
		avatarUrl: null,
		phone: "+63 924 222 3344",
		identityStatus: "expired" as const,
		certificateStatus: "revoked" as const,
		onboardingStep: "complete" as const,
		commissionNumber: "NC-2019-00012",
		commissionExpiry: "2023-01-15",
		subOrgId: "org_002",
		createdAt: lastMonth,
		updatedAt: lastWeek,
	},
	{
		id: "usr_client_003",
		email: "luis.ramos@example.com",
		name: "Luis Ramos",
		role: "client" as const,
		avatarUrl: null,
		phone: "+63 925 333 4455",
		identityStatus: "verified" as const,
		certificateStatus: "none" as const,
		onboardingStep: "complete" as const,
		commissionNumber: null,
		commissionExpiry: null,
		subOrgId: null,
		createdAt: lastWeek,
		updatedAt: now,
	},
	{
		id: "usr_client_004",
		email: "maria.lopez@example.com",
		name: "Maria Lopez",
		role: "client" as const,
		avatarUrl: null,
		phone: "+63 926 444 5566",
		identityStatus: "pending" as const,
		certificateStatus: "none" as const,
		onboardingStep: "profile" as const,
		commissionNumber: null,
		commissionExpiry: null,
		subOrgId: null,
		createdAt: yesterday,
		updatedAt: now,
	},
	{
		id: "usr_client_005",
		email: "jose.torres@example.com",
		name: "Jose Torres",
		role: "client" as const,
		avatarUrl: null,
		phone: "+63 927 555 6677",
		identityStatus: "verified" as const,
		certificateStatus: "none" as const,
		onboardingStep: "complete" as const,
		commissionNumber: null,
		commissionExpiry: null,
		subOrgId: null,
		createdAt: lastMonth,
		updatedAt: yesterday,
	},
	{
		id: "usr_client_006",
		email: "carmen.lim@example.com",
		name: "Carmen Lim",
		role: "client" as const,
		avatarUrl: null,
		phone: "+63 928 666 7788",
		identityStatus: "verified" as const,
		certificateStatus: "none" as const,
		onboardingStep: "complete" as const,
		commissionNumber: null,
		commissionExpiry: null,
		subOrgId: null,
		createdAt: lastWeek,
		updatedAt: lastWeek,
	},
	{
		id: "usr_client_007",
		email: "ricardo.tan@example.com",
		name: "Ricardo Tan",
		role: "client" as const,
		avatarUrl: null,
		phone: "+63 929 777 8899",
		identityStatus: "unverified" as const,
		certificateStatus: "none" as const,
		onboardingStep: "profile" as const,
		commissionNumber: null,
		commissionExpiry: null,
		subOrgId: null,
		createdAt: yesterday,
		updatedAt: now,
	},
	{
		id: "usr_client_008",
		email: "patricia.go@example.com",
		name: "Patricia Go",
		role: "client" as const,
		avatarUrl: null,
		phone: "+63 930 888 9900",
		identityStatus: "verified" as const,
		certificateStatus: "none" as const,
		onboardingStep: "complete" as const,
		commissionNumber: null,
		commissionExpiry: null,
		subOrgId: null,
		createdAt: lastMonth,
		updatedAt: lastMonth,
	},
	{
		id: "usr_client_009",
		email: "daniel.ong@example.com",
		name: "Daniel Ong",
		role: "client" as const,
		avatarUrl: null,
		phone: "+63 931 999 0011",
		identityStatus: "rejected" as const,
		certificateStatus: "none" as const,
		onboardingStep: "complete" as const,
		commissionNumber: null,
		commissionExpiry: null,
		subOrgId: null,
		createdAt: lastWeek,
		updatedAt: lastWeek,
	},
	{
		id: "usr_client_010",
		email: "grace.chua@example.com",
		name: "Grace Chua",
		role: "client" as const,
		avatarUrl: null,
		phone: "+63 932 000 1122",
		identityStatus: "verified" as const,
		certificateStatus: "none" as const,
		onboardingStep: "complete" as const,
		commissionNumber: null,
		commissionExpiry: null,
		subOrgId: null,
		createdAt: now,
		updatedAt: now,
	},
	{
		id: "usr_admin_001",
		email: "admin@qlegal.ph",
		name: "System Admin",
		role: "admin" as const,
		avatarUrl: null,
		phone: "+63 922 000 0001",
		identityStatus: "verified" as const,
		certificateStatus: "none" as const,
		onboardingStep: "complete" as const,
		commissionNumber: null,
		commissionExpiry: null,
		subOrgId: null,
		createdAt: lastMonth,
		updatedAt: now,
	},
]

export const mockHypervergeTransactions = [
	{
		id: "hv_001",
		userId: "usr_enp_001",
		status: "approved" as const,
		transactionId: "HV-TXN-2024-001",
		documentType: "Philippine National ID",
		confidence: 98,
		reason: null,
		createdAt: lastMonth,
		updatedAt: lastMonth,
	},
	{
		id: "hv_002",
		userId: "usr_enp_002",
		status: "pending" as const,
		transactionId: "HV-TXN-2024-002",
		documentType: "Philippine Passport",
		confidence: null,
		reason: null,
		createdAt: yesterday,
		updatedAt: now,
	},
	{
		id: "hv_003",
		userId: "usr_enp_003",
		status: "rejected" as const,
		transactionId: "HV-TXN-2024-003",
		documentType: "Driver License",
		confidence: 42,
		reason: "Document appears to be expired or tampered",
		createdAt: lastWeek,
		updatedAt: lastWeek,
	},
	{
		id: "hv_004",
		userId: "usr_client_001",
		status: "approved" as const,
		transactionId: "HV-TXN-2024-004",
		documentType: "Philippine National ID",
		confidence: 95,
		reason: null,
		createdAt: lastMonth,
		updatedAt: lastMonth,
	},
	{
		id: "hv_005",
		userId: "usr_enp_002",
		status: "needs_review" as const,
		transactionId: "HV-TXN-2024-005",
		documentType: "Philippine Passport",
		confidence: 65,
		reason: "Low confidence score — manual review recommended",
		createdAt: now,
		updatedAt: now,
	},
	{
		id: "hv_006",
		userId: "usr_client_009",
		status: "rejected" as const,
		transactionId: "HV-TXN-2024-006",
		documentType: "UMID",
		confidence: 22,
		reason: "Document unreadable / verification failed",
		createdAt: lastWeek,
		updatedAt: lastWeek,
	},
]
